[package]
name = "tailxid-assertion"
version = "0.1.0"
edition = "2021"

[dependencies]
deadpool-postgres = "0.14.0"
futures = "0.3.31"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-postgres = { version = "0.7.12", features = ["with-uuid-1"] }
uuid = "1.10.0"
